### ISSUE TITLE
error message ['function' object has no attribute 'Model']

### ISSUE THREAD

**Issue by Roboxkin** [Azazel0203/ocr_captcha#2]
Hello!
Please help me start training

All the actions I've taken:
1) Created a new project (ocr_service) in pycharm with a virtual environment
2) Cloned the project (git clone https://github.com/Azazel0203/ocr_captcha.git)
3) cd ocr_captcha
4) pip install -r requirements.txt

5) Added six new characters "+", "-", "*", "!", "@", "." to the file "artifact/unique_char.csv", "artifact/char_to_num.json", "artifact/num_to_char.json"

6) In the file "artifact/char_to_num.json" and "artifact/num_to_char.json" corrected "vocabulary_size": 32 to "vocabulary_size": 38

unique_char.csv file:
![Screenshot](https://github.com/Azazel0203/ocr_captcha/assets/39112555/820a3be4-a836-4886-8138-946394f320f3)

This is how I have my files now "artifact/char_to_num.json" and "artifact/num_to_char.json"

```Pythot
{"config": {"name": "string_lookup_1", "trainable": true, "dtype": "float32", "invert": true, "max_tokens": null, "num_oov_indices": 1, "oov_token": "[UNK]", "mask_token": null, "output_mode": "int", "sparse": false, "pad_to_max_tokens": false, "idf_weights": null, "vocabulary": ["[UNK]", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F", "G", "H", "J", "K", "M", "N", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "+", "-", "*", "!", "@", "."], "vocabulary_size": 38, "encoding": "utf-8"}, "weights": []}
```
7) Created a train folder in the {project name}/ocr captcha directory

8) Added the file "labels.csv" to the train folder
![Screenshot](https://github.com/Azazel0203/ocr_captcha/assets/39112555/edf32b6d-5812-43ae-a7cf-3a05885ba3b4)

9) Created an images folder in the train directory and placed 93 pictures in it
![Screenshot](https://github.com/Azazel0203/ocr_captcha/assets/39112555/c5a43fc6-4e84-4575-87c3-7222b56f3c1e)

10) In the file "data_ingestion.py" I corrected the paths and the cycle
![Screenshot](https://github.com/Azazel0203/ocr_captcha/assets/39112555/886fb959-16b0-47a7-83b3-59200a582875)

11) Manually added the necessary data to the files (I don't know how correct this is) "raw_img_path.csv", "raw_labels.csv", "test_x.csv", "test_y.csv", "train_x.csv", "train_y.csv"

12) In the file "model_trainer.py" I changed the line with the sizes of the pictures
![Screenshot_1](https://github.com/Azazel0203/ocr_captcha/assets/39112555/3a55fb82-6081-4e7d-9a90-a339218023b7)

13) I run the file "data_ingestion.py", there are no errors

14) I run the file "model_trainer.py" and get errors
```Python
D:\ocr_service\.venv\Scripts\python.exe D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py 
2024-05-07 09:25:38.677735: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-07 09:25:39.712543: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-07 09:25:41.673057: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 82, in initate_model_training
    model = build_model(self.img_width, self.img_height, char_to_num) 
  File "D:\ocr_service\ocr_captcha\src\ocr_captcha\utils\utils.py", line 178, in build_model
    model = keras.models.Model(
AttributeError: 'function' object has no attribute 'Model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 129, in <module>
    model_path = trainer.initate_model_training(train_path_x, train_path_y, test_path_x, test_path_y, unique_chars)
  File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 119, in initate_model_training
    raise customexception(e, sys)
ocr_captcha.src.ocr_captcha.exception.exception.customexception: Error occured in python script | 
 name [D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py] 
 line number [82] 
 error message ['function' object has no attribute 'Model']

Process finished with exit code 1
```
15) In the file "model_trainer.py" line 15 is highlighted as an error
![Screenshot_2](https://github.com/Azazel0203/ocr_captcha/assets/39112555/c080b67c-e4c3-4eb7-b13e-f4df39263960)

16) You have written "inference/: Module for making predictions on new images.", there is no such file

What am I doing wrong?
Please help me start training and then test the model.
I would be grateful for any help!
Thank you

Python version 3.10.11
Windows 11 x64
no GPU

**Comment by Azazel0203** [comment]
> Hello! Please help me start training
> 
> All the actions I've taken:
> 
> 1. Created a new project (ocr_service) in pycharm with a virtual environment
> 2. Cloned the project (git clone https://github.com/Azazel0203/ocr_captcha.git)
> 3. cd ocr_captcha
> 4. pip install -r requirements.txt
> 5. Added six new characters "+", "-", "*", "!", "@", "." to the file "artifact/unique_char.csv", "artifact/char_to_num.json", "artifact/num_to_char.json"
> 6. In the file "artifact/char_to_num.json" and "artifact/num_to_char.json" corrected "vocabulary_size": 32 to "vocabulary_size": 38
> 
> unique_char.csv file: ![Screenshot](https://private-user-images.githubusercontent.com/39112555/328422676-820a3be4-a836-4886-8138-946394f320f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDc0NjksIm5iZiI6MTcxNTEwNzE2OSwicGF0aCI6Ii8zOTExMjU1NS8zMjg0MjI2NzYtODIwYTNiZTQtYTgzNi00ODg2LTgxMzgtOTQ2Mzk0ZjMyMGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE4MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxOTZkZTk1ZGRjMGNkODllYmU1ZjVlYTUxMzIxN2I5YTkzMzEyMTNmNmFmM2JhOWQ4MmFhMDExMDUzYTNlZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xm4rf7BgQY7kLaAhsNOaUadEa2MPmzqIDveXH59v5IQ)
> 
> This is how I have my files now "artifact/char_to_num.json" and "artifact/num_to_char.json"
> 
> ```
> {"config": {"name": "string_lookup_1", "trainable": true, "dtype": "float32", "invert": true, "max_tokens": null, "num_oov_indices": 1, "oov_token": "[UNK]", "mask_token": null, "output_mode": "int", "sparse": false, "pad_to_max_tokens": false, "idf_weights": null, "vocabulary": ["[UNK]", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F", "G", "H", "J", "K", "M", "N", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "+", "-", "*", "!", "@", "."], "vocabulary_size": 38, "encoding": "utf-8"}, "weights": []}
> ```
> 
> 7. Created a train folder in the {project name}/ocr captcha directory
> 8. Added the file "labels.csv" to the train folder
>    ![Screenshot](https://private-user-images.githubusercontent.com/39112555/328429185-edf32b6d-5812-43ae-a7cf-3a05885ba3b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDc0NjksIm5iZiI6MTcxNTEwNzE2OSwicGF0aCI6Ii8zOTExMjU1NS8zMjg0MjkxODUtZWRmMzJiNmQtNTgxMi00M2FlLWE3Y2YtM2EwNTg4NWJhM2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE4MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZDUyYjg0YmJiY2M1OTkwYzVmNTIyOGJjYjUxOTYzY2I0ZjAyNjgyYmNmMjAzZGE3ZGI3ZDgyZGNjNWNlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ob53C-mzG1bZhc4l5lJzuLAKnlljHfTIaX7m1vht2JA)
> 9. Created an images folder in the train directory and placed 93 pictures in it
>    ![Screenshot](https://private-user-images.githubusercontent.com/39112555/328430277-c5a43fc6-4e84-4575-87c3-7222b56f3c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDc0NjksIm5iZiI6MTcxNTEwNzE2OSwicGF0aCI6Ii8zOTExMjU1NS8zMjg0MzAyNzctYzVhNDNmYzYtNGU4NC00NTc1LTg3YzMtNzIyMmI1NmYzYzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE4MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNzlmNDY5NzJiYjQ1MWY4ODViODdjMDFhNjJhNTM3Y2I4ZGM1N2Q1MmFlMmMzYjAyZWQ3Nzg0NTA1NmIxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RqWGMFXwORpEAjh3aippCzIJj4z2t_k0O8O38unUKls)
> 10. In the file "data_ingestion.py" I corrected the paths and the cycle
>     ![Screenshot](https://private-user-images.githubusercontent.com/39112555/328431520-886fb959-16b0-47a7-83b3-59200a582875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDc0NjksIm5iZiI6MTcxNTEwNzE2OSwicGF0aCI6Ii8zOTExMjU1NS8zMjg0MzE1MjAtODg2ZmI5NTktMTZiMC00N2E3LTgzYjMtNTkyMDBhNTgyODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE4MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MmVmYTkzNzMwM2VlN2I3MzJjYmQyY2FkYzgwMDZmZWQ1ZjhmODZhZmRkZDdhMTRiMTlkZjlhODdmZmQ5MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7NK5R--1OFWk0lIGPXnhX_14gnyAWLshCR1dxLE8Ju4)
> 11. Manually added the necessary data to the files (I don't know how correct this is) "raw_img_path.csv", "raw_labels.csv", "test_x.csv", "test_y.csv", "train_x.csv", "train_y.csv"
> 12. In the file "model_trainer.py" I changed the line with the sizes of the pictures
>     ![Screenshot_1](https://private-user-images.githubusercontent.com/39112555/328437162-3a55fb82-6081-4e7d-9a90-a339218023b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDc0NjksIm5iZiI6MTcxNTEwNzE2OSwicGF0aCI6Ii8zOTExMjU1NS8zMjg0MzcxNjItM2E1NWZiODItNjA4MS00ZTdkLTlhOTAtYTMzOTIxODAyM2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE4MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMGJhMGIxODg1NzY1MjkwYThiZThmZjJhOTQ2NTc3ODllMzllYmVlNjJmZDZhMjE1N2U3OTlmYjJhODZiODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5appjn1I8_V-mi3iHm58zeaAtqTsNXV6PAaUrAsMwHc)
> 13. I run the file "data_ingestion.py", there are no errors
> 14. I run the file "model_trainer.py" and get errors
> 
> ```python
> D:\ocr_service\.venv\Scripts\python.exe D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py 
> 2024-05-07 09:25:38.677735: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 2024-05-07 09:25:39.712543: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 2024-05-07 09:25:41.673057: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> Traceback (most recent call last):
>   File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 82, in initate_model_training
>     model = build_model(self.img_width, self.img_height, char_to_num) 
>   File "D:\ocr_service\ocr_captcha\src\ocr_captcha\utils\utils.py", line 178, in build_model
>     model = keras.models.Model(
> AttributeError: 'function' object has no attribute 'Model'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 129, in <module>
>     model_path = trainer.initate_model_training(train_path_x, train_path_y, test_path_x, test_path_y, unique_chars)
>   File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 119, in initate_model_training
>     raise customexception(e, sys)
> ocr_captcha.src.ocr_captcha.exception.exception.customexception: Error occured in python script | 
>  name [D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py] 
>  line number [82] 
>  error message ['function' object has no attribute 'Model']
> 
> Process finished with exit code 1
> ```
> 
> 15. In the file "model_trainer.py" line 15 is highlighted as an error
>     ![Screenshot_2](https://private-user-images.githubusercontent.com/39112555/328439765-c080b67c-e4c3-4eb7-b13e-f4df39263960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDc0NjksIm5iZiI6MTcxNTEwNzE2OSwicGF0aCI6Ii8zOTExMjU1NS8zMjg0Mzk3NjUtYzA4MGI2N2MtZTRjMy00ZWI3LWIxM2UtZjRkZjM5MjYzOTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE4MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNjFlMzUxYzhlNDQyMmFhZmE1ZWFmYmY3YzNjZWZlN2I0ZTk5MmJhOWViODhhZmY2MmZhOTA3OGU3MTA4NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9PblDib9UEDTFIqOpQUbKfiY6UMQJRu0qgnuzu46WU)
> 16. You have written "inference/: Module for making predictions on new images.", there is no such file
> 
> What am I doing wrong? Please help me start training and then test the model. I would be grateful for any help! Thank you
> 
> Python version 3.10.11 Windows 11 x64 no GPU

You shouldn't manually change the json files in the artifacts. The data-ingestion part does it for you.
Also you shouldn't be changing the paths. Only path you should update is the path to the main data (training and testing data).
Rest all the things are supposed to run as it is.

Also delete the artifact folder and then create a new folder name artifact to proceed.
As your data is of different kind, You would need to create different artifacts.

**Comment by Roboxkin** [comment]
Thank you very much for the answer!
  deleted the artifact folder, then ran the data_ingestion.py file, after which the artifact folder was created with all the files.
Then I ran the model_trainer.py file and got the error

```Python
D:\ocr_service\.venv\Scripts\python.exe D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py 
2024-05-08 04:14:12.360207: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-08 04:14:13.353849: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-08 04:14:15.140182: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 82, in initate_model_training
    model = build_model(self.img_width, self.img_height, char_to_num) 
  File "D:\ocr_service\ocr_captcha\src\ocr_captcha\utils\utils.py", line 178, in build_model
    model = keras.models.Model(
AttributeError: 'function' object has no attribute 'Model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 129, in <module>
    model_path = trainer.initate_model_training(train_path_x, train_path_y, test_path_x, test_path_y, unique_chars)
  File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 119, in initate_model_training
    raise customexception(e, sys)
ocr_captcha.src.ocr_captcha.exception.exception.customexception: Error occured in python script | 
 name [D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py] 
 line number [82] 
 error message ['function' object has no attribute 'Model']

Process finished with exit code 1
```

**Comment by Azazel0203** [comment]
> Thank you very much for the answer!
>   deleted the artifact folder, then ran the data_ingestion.py file, after which the artifact folder was created with all the files.
> Then I ran the model_trainer.py file and got the error
> 
> ```Python
> D:\ocr_service\.venv\Scripts\python.exe D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py 
> 2024-05-08 04:14:12.360207: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 2024-05-08 04:14:13.353849: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 2024-05-08 04:14:15.140182: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> Traceback (most recent call last):
>   File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 82, in initate_model_training
>     model = build_model(self.img_width, self.img_height, char_to_num) 
>   File "D:\ocr_service\ocr_captcha\src\ocr_captcha\utils\utils.py", line 178, in build_model
>     model = keras.models.Model(
> AttributeError: 'function' object has no attribute 'Model'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 129, in <module>
>     model_path = trainer.initate_model_training(train_path_x, train_path_y, test_path_x, test_path_y, unique_chars)
>   File "D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py", line 119, in initate_model_training
>     raise customexception(e, sys)
> ocr_captcha.src.ocr_captcha.exception.exception.customexception: Error occured in python script | 
>  name [D:\ocr_service\ocr_captcha\src\ocr_captcha\components\model_trainer.py] 
>  line number [82] 
>  error message ['function' object has no attribute 'Model']
> 
> Process finished with exit code 1
> ```

Install the requirements_dev and try.

**Comment by Roboxkin** [comment]
I installed it, but it didn't help
![Screenshot](https://github.com/Azazel0203/ocr_captcha/assets/39112555/51254844-3011-4df0-93d1-99d24006c0cf)

**Comment by Azazel0203** [comment]
> I installed it, but it didn't help ![Screenshot](https://private-user-images.githubusercontent.com/39112555/328729573-51254844-3011-4df0-93d1-99d24006c0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzk5MjYsIm5iZiI6MTcxNTEzOTYyNiwicGF0aCI6Ii8zOTExMjU1NS8zMjg3Mjk1NzMtNTEyNTQ4NDQtMzAxMS00ZGYwLTkzZDEtOTlkMjQwMDZjMGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAzNDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNmI1NzcxZGFjNDg5ODNjZDY0ZjZmZWQ5NTU1OWViOGFjMDRkYTZiNDYwMDhiMGUxOGQyNzllN2EyN2M0YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gqIsT5JpqXJDUUMBVBx8jwXoF_3G7uGNqatOaOP8I4U)


I am a bit busy right now...i will check the code again and get back to you by tomorrow.

**Comment by Roboxkin** [comment]
> > Я установил, но это не помогло![Скриншот](https://private-user-images.githubusercontent.com/39112555/328729573-51254844-3011-4df0-93d1-99d24006c0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzk5MjYsIm5iZiI6MTcxNTEzOTYyNiwicGF0aCI6Ii8zOTExMjU1NS8zMjg3Mjk1NzMtNTEyNTQ4NDQtMzAxMS00ZGYwLTkzZDEtOTlkMjQwMDZjMGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAzNDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNmI1NzcxZGFjNDg5ODNjZDY0ZjZmZWQ5NTU1OWViOGFjMDRkYTZiNDYwMDhiMGUxOGQyNzllN2EyN2M0YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gqIsT5JpqXJDUUMBVBx8jwXoF_3G7uGNqatOaOP8I4U)
> 
> Я сейчас немного занят... я проверю код еще раз и свяжусь с вами завтра.

Thanks a lot

**Comment by Roboxkin** [comment]
I understand that the project can be deleted.

**Comment by Azazel0203** [comment]
> I understand that the project can be deleted.

What do u mean? 



I am still held back with my college..i am gonna check the code when i am free.

**Comment by Roboxkin** [comment]
I mean, you promised to contact me the next day, but you didn't do anything.
I understand that you don't have to, but you promised.
Think for yourself, what should I think in such a situation?
As a user, I received errors that I am not able to fix myself.
You, as the author, can correct them, you promised to look and correct them if possible, you promise to look into it and report it the next day, several days have passed and you are silent.
What should you think in such a situation?

**Comment by Azazel0203** [comment]
> I mean, you promised to contact me the next day, but you didn't do anything.
> I understand that you don't have to, but you promised.
> Think for yourself, what should I think in such a situation?
> As a user, I received errors that I am not able to fix myself.
> You, as the author, can correct them, you promised to look and correct them if possible, you promise to look into it and report it the next day, several days have passed and you are silent.
> What should you think in such a situation?

Well i have been busy with my college exams..
I will look into it today... Don't worry

Abe also it's not that you can't fix the error... You can always make a PR to fix the error.

**Comment by Roboxkin** [comment]
> > I mean, you promised to contact me the next day, but you didn't do anything.
> > I understand that you don't have to, but you promised.
> > Think for yourself, what should I think in such a situation?
> > As a user, I received errors that I am not able to fix myself.
> > You, as the author, can correct them, you promised to look and correct them if possible, you promise to look into it and report it the next day, several days have passed and you are silent.
> > What should you think in such a situation?
> 
> Well i have been busy with my college exams.. I will look into it today... Don't worry
> 
> Abe also it's not that you can't fix the error... You can always make a PR to fix the error.

Don't think anything bad, I'm writing through Google translator.
I'm not a professional programmer, I'm just learning.
Thanks a lot

**Comment by Azazel0203** [comment]
> > > I mean, you promised to contact me the next day, but you didn't do anything.
> > > I understand that you don't have to, but you promised.
> > > Think for yourself, what should I think in such a situation?
> > > As a user, I received errors that I am not able to fix myself.
> > > You, as the author, can correct them, you promised to look and correct them if possible, you promise to look into it and report it the next day, several days have passed and you are silent.
> > > What should you think in such a situation?
> > 
> > 
> > Well i have been busy with my college exams.. I will look into it today... Don't worry
> > Abe also it's not that you can't fix the error... You can always make a PR to fix the error.
> 
> Don't think anything bad, I'm writing through Google translator. I'm not a professional programmer, I'm just learning. Thanks a lot

ohh so whats ur native language

Also I tried running it on my local...and its running fine
![image](https://github.com/Azazel0203/ocr_captcha/assets/139248351/59acdf22-c56c-4c8d-aae9-1e89169b47ab)

So i cant recreate the error.
Tell me a way I can contact You properly to sort this problem of yours...Do you have discord?

**Comment by Roboxkin** [comment]
My native Russian language)
Can I ask you to check my project?
It contains everything that I wrote to you and all the pictures.
It’s possible, of course, that you have something installed that I don’t, because it can’t be that it works for one person, but not for another.

The project turned out to be 38mb, git does not allow more than 25mb, I had to upload an exchanger to the file
![Screenshot](https://github.com/Azazel0203/ocr_captcha/assets/39112555/b4558420-4145-4ac2-abe0-d5eae940546f)

https://transfiles.ru/h9sg3

**Comment by Roboxkin** [comment]
My discord name Robox

![Screenshot](https://github.com/Azazel0203/ocr_captcha/assets/39112555/ca246fa7-4891-4f54-82aa-1cc4fc51c8e4)
